### ISSUE TITLE
Enhanced block quote and Quick commands not working

### ISSUE THREAD

**Issue by Jae0143** [SeptemberHX/joplin-plugin-enhancement#6] opened 2022-06-11 03:58 UTC
Everything enabled and those two features seem to be not working

**Comment by SeptemberHX** [comment] 2022-06-11 04:12
Enhanced block quote feature is pushed to the repo, but not published yet. I am still working on it to avoid potential bugs, and it should work in the next release.

For quick commands, have you restarted your joplin application after enable quick commands feature? Some hints should popup when typing character '/'

**Comment by Jae0143** [comment] 2022-06-11 04:16
Ah ok. For quick commands, nothing seems to show up when I type /.

**Comment by SeptemberHX** [comment] 2022-06-11 06:10
What is your OS and joplin's version ?

**Comment by Jae0143** [comment] 2022-06-11 11:31
MacOS 12.4, Joplin 2.8.8

**Comment by SeptemberHX** [comment] 2022-06-12 04:19
Tested on MacOS 11.3, Joplin 2.8.8. But I cannot reproduce the problem.

Can you open 'Tools -> Open developer tools -> Console' and check whether there exists messages related to 'enhancement' in red color?

**Comment by Jae0143** [comment] 2022-06-12 07:02
<img width="550" alt="Screen Shot 2022-06-12 at 16 02 28" src="https://user-images.githubusercontent.com/39797496/173221545-ae1805da-a536-491a-8fcb-9cfcae4cddeb.png">

**Comment by SeptemberHX** [comment] 2022-06-12 09:35
I think I figured it out. The fix was pushed to the repo, and it will be in the next release.

Before next release, you can install the plugin `note link system` to make the quick commands work.

**Comment by SeptemberHX** [comment] 2022-06-17 02:01
It should be fixed now in v0.8.1

**Closed** 2022-06-28 08:45 UTC
